##  -*-  coding: utf-8; mode: ruby -*-  ##
##  vi: set ft=ruby

load  File.expand_path("DetectOS.rb")  if File.exists?("DetectOS.rb")

Vagrant.configure("2") do |config|
  config.vm.box = "takahiro-itou/centos7-develop"

  config.vm.provider "virtualbox" do |v|
    v.name   = "vagrant-centos7-develop"
    v.memory = "3072"

    v.gui    = false
  end


  config.vm.network(:forwarded_port, guest: 22, host: 15022, id: "ssh")
  config.vm.network("private_network", ip: "192.168.33.50")
  config.vm.synced_folder(".", "/vagrant", disabled: true)

load  File.expand_path('common/CommonCustomize.rb')

# Provisioning(s)
load  File.expand_path('common/UploadFiles.rb')

Vagrant.configure("2") do |config|
  config.vm.provision("root", type: "shell",
                      path: "provision.root.sh",
                      privileged: true)
  config.vm.provision("user", type: "shell",
                      path: "provision.user.sh",
                      privileged: false)
  config.vm.provision("hguser", type: "shell",
                      path: "provision.hguser.sh",
                      privileged: false)
end

